services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"

  publisher:
    build: ./publisher
    depends_on:
      - backend

  frontend:
    image: nginx:alpine
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    ports:
      - "8080:80"
    depends_on:
      - backend
